#!/usr/bin/env python3
"""Compile every example, run it, and hold its output to a recorded answer key.

This is the spine of the library. A lesson page never hand-types what a program
prints; it marks the spot and this tool fills it from a real run:

    <!-- output:option_vs_result -->
    <!-- /output -->

Inside the markers is generated, outside is yours.

Three modes
-----------
    python3 tools/run_examples.py             verify + refill the .md blocks
    python3 tools/run_examples.py --update    accept current output as the key
    python3 tools/run_examples.py --check     write nothing; fail on any drift  (CI)

An example is any ``*.rs`` under a folder named ``examples/``. Its answer key is
the sibling ``<stem>.out``. Stems must be unique repo-wide, because a Markdown
block names a bare stem with no path — the same rule the star-voting-library uses
for its generated case pages.

Stdlib only, on purpose: the docs build already needs Python, and a teaching repo
should not make you install a toolchain to read it.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
EDITION = "2024"

# <!-- output:stem -->  ...generated...  <!-- /output -->
BLOCK = re.compile(
    r"(?P<open><!--\s*output:(?P<stem>[A-Za-z0-9_\-]+)\s*-->)"
    r"(?P<body>.*?)"
    r"(?P<close><!--\s*/output\s*-->)",
    re.DOTALL,
)

SKIP_DIRS = {".git", "site", ".venv", "target", "__pycache__", ".github"}

# A fenced code block, opened or closed. Needed because the pages that DOCUMENT
# this mechanism (README.md, CONTRIBUTING.md) show the markers as examples inside
# a fence — those must be left alone, not treated as blocks to fill.
FENCE = re.compile(r"^[ \t]*(?P<f>`{3,}|~{3,})", re.MULTILINE)


def fenced_spans(text: str) -> list[tuple[int, int]]:
    """Character ranges covered by fenced code blocks."""
    spans: list[tuple[int, int]] = []
    open_at: int | None = None
    open_fence = ""
    for m in FENCE.finditer(text):
        fence = m.group("f")
        if open_at is None:
            open_at, open_fence = m.start(), fence
        elif fence[0] == open_fence[0] and len(fence) >= len(open_fence):
            spans.append((open_at, m.end()))
            open_at = None
    if open_at is not None:
        spans.append((open_at, len(text)))
    return spans


def walk(root: Path):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            yield Path(dirpath) / name


def find_examples() -> dict[str, Path]:
    """Map stem -> path for every .rs under an examples/ folder. Stems are unique."""
    found: dict[str, Path] = {}
    for path in sorted(walk(REPO)):
        if path.suffix != ".rs" or path.parent.name != "examples":
            continue
        stem = path.stem
        if stem in found:
            sys.exit(
                f"ERROR: duplicate example stem {stem!r}\n"
                f"  {found[stem].relative_to(REPO)}\n  {path.relative_to(REPO)}\n"
                "Stems are named bare in Markdown blocks, so they must be unique."
            )
        found[stem] = path
    return found


def run_example(src: Path, workdir: Path) -> str:
    """Compile and run one example; return its stdout. Exits on failure."""
    binary = workdir / src.stem
    build = subprocess.run(
        ["rustc", "--edition", EDITION, str(src), "-o", str(binary)],
        capture_output=True,
        text=True,
    )
    if build.returncode != 0:
        sys.exit(f"ERROR: {src.relative_to(REPO)} failed to compile\n{build.stderr}")
    if build.stderr.strip():
        print(f"  note: {src.relative_to(REPO)} compiled with warnings:\n{build.stderr}")

    run = subprocess.run([str(binary)], capture_output=True, text=True, timeout=60)
    if run.returncode != 0:
        sys.exit(
            f"ERROR: {src.relative_to(REPO)} exited {run.returncode}\n{run.stderr}"
        )
    return run.stdout


def rendered_block(stem: str, src: Path, output: str, page: Path) -> str:
    """The generated body that goes between the markers on `page`."""
    href = os.path.relpath(src, page.parent)
    body = output.strip("\n")
    return (
        f"\n*Verified output of [`{src.name}`]({href}) — regenerated by "
        f"`tools/run_examples.py`, never hand-typed.*\n\n"
        f"```text\n{body}\n```\n"
    )


def fill_pages(outputs: dict[str, str], sources: dict[str, Path], write: bool) -> list[str]:
    """Refill every output block on every Markdown page. Returns drift descriptions."""
    drift: list[str] = []
    for page in sorted(walk(REPO)):
        if page.suffix != ".md":
            continue
        text = page.read_text(encoding="utf-8")
        if "<!-- output:" not in text:
            continue
        skip = fenced_spans(text)

        def replace(m: re.Match) -> str:
            # A marker shown as an example inside a code fence is documentation,
            # not a block to fill.
            if any(lo <= m.start() < hi for lo, hi in skip):
                return m.group(0)
            stem = m.group("stem")
            if stem not in outputs:
                sys.exit(
                    f"ERROR: {page.relative_to(REPO)} asks for output block {stem!r}, "
                    "but no examples/*.rs has that stem."
                )
            return (
                m.group("open")
                + rendered_block(stem, sources[stem], outputs[stem], page)
                + m.group("close")
            )

        new = BLOCK.sub(replace, text)
        if new != text:
            drift.append(str(page.relative_to(REPO)))
            if write:
                page.write_text(new, encoding="utf-8")
    return drift


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--update", action="store_true", help="record current output as the answer key")
    ap.add_argument("--check", action="store_true", help="write nothing; fail on drift (CI)")
    args = ap.parse_args()

    examples = find_examples()
    if not examples:
        print("No examples found (looked for *.rs under any examples/ folder).")
        return 0

    outputs: dict[str, str] = {}
    failures: list[str] = []

    with tempfile.TemporaryDirectory() as tmp:
        workdir = Path(tmp)
        for stem, src in examples.items():
            actual = run_example(src, workdir)
            outputs[stem] = actual
            key = src.with_suffix(".out")

            if args.update:
                key.write_text(actual, encoding="utf-8")
                print(f"  recorded  {key.relative_to(REPO)}")
                continue

            if not key.exists():
                failures.append(f"{src.relative_to(REPO)}: no answer key — run with --update")
                continue
            if key.read_text(encoding="utf-8") != actual:
                failures.append(
                    f"{src.relative_to(REPO)}: output differs from {key.name}"
                )
            else:
                print(f"  ok        {src.relative_to(REPO)}")

    drift = fill_pages(outputs, examples, write=not args.check)

    if args.check and drift:
        failures.append(
            "Markdown output blocks are stale: " + ", ".join(drift)
            + " — run tools/run_examples.py"
        )
    elif drift:
        for page in drift:
            print(f"  filled    {page}")

    if failures:
        print("\nFAILED:")
        for f in failures:
            print(f"  - {f}")
        return 1

    print(f"\n{len(examples)} example(s) verified against their recorded output.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
